version: "3.6"
services:
  traefik:
    image: traefik:alpine
    command: --api
    depends_on:
      - openssl
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./traefik/:/traefik/
      - ssl:/ssl
    networks:
      - traefik
  dnsmasq:
    image: andyshinn/dnsmasq
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    cap_add:
      - NET_ADMIN
    environment:
      - ADDRESSES # to use multiple domains, separate them with slash. for includes subdomains, start with dot.
      - IP_ADDR
    command: [
      "--no-hosts",
      "--address=/${ADDRESSES:-.local.ridi.io}/${IP_ADDR:-127.0.0.1}"
    ]
  openssl:
    image: frapsoft/openssl
    volumes:
      - ./ssl/:/pem/
      - ./openssl-entrypoint.sh:/docker-entrypoint.sh
      - ssl:/ssl
    entrypoint: /bin/sh -c /docker-entrypoint.sh
volumes:
  ssl:
networks:
  traefik:
    external:
      name: ${EXTERNAL_NETWORK:-ridi}
